const state={tab:'chat',classId:null,slotId:null,threadId:null,staff:[],classes:[],slots:[],students:[],threads:[],messages:[],filter:'all',editing:null,chatUnsub:null};
const el=id=>document.getElementById(id);
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clock=v=>{const ms=stamp(v);if(!ms)return'';const d=new Date(ms);return d.getDate()+'/'+(d.getMonth()+1)+' '+d.getHours()+':'+String(d.getMinutes()).padStart(2,'0');};
const nameOf=k=>{const s=state.staff.find(x=>x.key===k||x.id===k);return s?s.name:(k||'unknown');};
function tabsFor(caps){const t=[['chat','Chat']];if(caps.timetable!=='none')t.push(['timetable','Timetable']);if(caps.students!=='none')t.push(['students','Students']);return t;}
async function boot(){const a=el('app');if(a)a.innerHTML='<p class="pad">Loading...</p>';if(await store.start())render();else renderLogin();}
function renderLogin(m){const a=el('app');if(!a)return;a.innerHTML='<div class="signin"><h1>School Brain</h1><p class="muted">Sign in to continue.</p><form id="signin" class="stack"><label>Email<input name="id" type="email" autocomplete="username" placeholder="management@school.brain" required></label><label>Password<input name="pass" placeholder="password" required type="password" autocomplete="current-password" required></label><button class="primary" type="submit" id="signinbtn">Sign in</button></form>'+(m?'<p class="error">'+esc(m)+'</p>':'')+'<p class="muted">Simulation login</p></div>';}
async function render(){const me=store.session;if(!tabsFor(me.caps).some(([id])=>id===state.tab))state.tab='chat';const a=el('app');if(!a)return;a.innerHTML='<header><b>School Brain</b><nav>'+tabsFor(me.caps).map(([id,l])=>'<button data-tab="'+id+'"'+(id===state.tab?' aria-current=page':'')+'>'+l+'</button>').join('')+'</nav><span class="grow"></span><span class="muted">'+esc(me.name)+' &middot; '+me.caps.label+'</span>'+(me.caps.students==='edit'?'<button data-seed>Seed data</button>':'')+'<button data-out>Sign out</button></header><main id="view"><p class="pad muted">Loading...</p></main>';renderTab();}
function unsubChat(){if(state.chatUnsub){try{state.chatUnsub();}catch(e){}state.chatUnsub=null;}}
async function renderTab(){const v=el('view');if(!v)return;try{unsubChat();await loadBase();if(state.tab==='chat')await renderChat(v);else if(state.tab==='timetable')await renderTimetable(v);else await renderStudents(v);}catch(err){v.innerHTML='<p class="pad error">'+esc(String(err.message||err))+'</p>';}}
async function loadBase(){state.staff=await store.staff();state.classes=await store.classes();if(!state.classId&&state.classes.length)state.classId=state.classes[0].id;}
async function refresh(){await renderTab();}
async function renderChat(view){state.threads=await store.threads();if(!state.threads.some(t=>t.id===state.threadId))state.threadId=(state.threads[0]||{}).id||null;state.messages=state.threadId?await store.messages(state.threadId):[];const me=store.session.staffKey;const thread=state.threads.find(t=>t.id===state.threadId);view.innerHTML='<div class="split"><aside class="side"><h2>Threads</h2>'+state.threads.map(t=>'<button class="thread'+(t.id===state.threadId?' on':'')+'" data-thread="'+esc(t.id)+'">'+esc(t.title)+' <span class="muted">'+(t.canPost?'member':'observing')+'</span></button>').join('')+(state.threads.length?'':'<p class="pad muted">No threads</p>')+'</aside><section class="col">'+(thread?'<h2>'+esc(thread.title)+(thread.canPost?'':' &middot; read only')+'</h2><div class="messages">'+(state.messages.length?state.messages.map(m=>'<div class="msg'+(m.from===me?' mine':'')+'"><small>'+esc(nameOf(m.from))+' &middot; '+clock(m.createdAt)+'</small><div>'+esc(m.text)+'</div></div>').join(''):'<p class="pad muted">No messages yet</p>')+'</div>'+(thread.canPost?'<form id="composer" class="row"><input name="text" placeholder="Type a message" required><button class="primary" type="submit">Send</button></form>':'<p class="pad muted">Read only</p>'):'<p class="pad muted">Pick a thread</p>')+'</section></div>';const box=view.querySelector('.messages');if(box)box.scrollTop=box.scrollHeight;if(state.threadId){state.chatUnsub=store.subscribeChat(state.threadId,m=>{state.messages.push(m);const mv=view.querySelector('.messages');if(mv){mv.innerHTML=state.messages.map(x=>'<div class="msg'+(x.from===me?' mine':'')+'"><small>'+esc(nameOf(x.from))+' &middot; '+clock(x.createdAt)+'</small><div>'+esc(x.text)+'</div></div>').join('');mv.scrollTop=mv.scrollHeight;}});}}
async function renderTimetable(view){const caps=store.session.caps;state.slots=caps.timetable==='own'?await store.mySlots():await store.slots(state.classId);view.innerHTML='<div class="row"><h2 class="grow">'+(caps.timetable==='own'?'My lessons':'Timetable')+'</h2>'+(caps.timetable==='edit'?'<label>Class<select data-class>'+state.classes.map(c=>'<option value="'+esc(c.id)+'"'+(c.id===state.classId?' selected':'')+'>'+esc(c.name)+'</option>').join('')+'</select></label>':'')+'</div>'+(caps.timetable==='own'?ownTimetable():gridTimetable(caps));}
function ownTimetable(){const rows=DAYS.map(d=>{const l=state.slots.filter(s=>s.day===d).sort((a,b)=>a.period-b.period);return '<tr><th>'+d+'</th><td>'+(l.length?l.map(s=>PERIODS[s.period][0]+' '+esc(s.subject)+' ('+esc(s.room)+')').join(' &middot; '):'&mdash;')+'</td></tr>';}).join('');return '<table class="grid"><tbody>'+rows+'</tbody></table>';}
function gridTimetable(caps){const cell=(day,p)=>{const s=state.slots.find(x=>x.day===day&&x.period===p);if(!s)return '<td class="muted">&mdash;</td>';const b='<b>'+esc(s.subject)+'</b><br><small>'+esc(nameOf(s.teacherKey))+'</small><br><small class="muted">'+esc(s.room)+'</small>';return caps.timetable==='edit'?'<td><button class="cell'+(state.slotId===s.id?' on':'')+'" data-slot="'+esc(s.id)+'">'+b+'</button></td>':'<td>'+b+'</td>';};const rows=PERIODS.map(([, [st,en]],pi)=>'<tr><th>'+st+'&ndash;'+en+'</th>'+DAYS.map(d=>cell(d,pi)).join('')+'</tr>').join('');const ch=state.slots.find(s=>s.id===state.slotId);const elig=ch?state.staff.filter(s=>(s.subjects||[]).includes(ch.subject)):[];return '<table class="grid"><thead><tr><th>Time</th>'+DAYS.map(d=>'<th>'+d+'</th>').join('')+'</tr></thead><tbody>'+rows+'</tbody></table>'+(ch?'<form id="assign" class="row"><b class="grow">'+esc(ch.day)+' '+PERIODS[ch.period][0]+' &middot; '+esc(ch.subject)+'</b><label>Teacher<select name="teacher">'+elig.map(s=>'<option value="'+esc(s.key)+'"'+(s.key===ch.teacherKey?' selected':'')+'>'+esc(s.name)+'</option>').join('')+'</select></label><button class="primary" type="submit">Save</button><button type="button" data-clear>Cancel</button></form>':'<p class="pad muted">Select lesson</p>');}
async function renderStudents(view){state.students=await store.students();const canEdit=store.session.caps.students==='edit';const rows=state.students.filter(s=>state.filter==='marks'?s.lowMarks:state.filter==='attendance'?s.lowAttendance:true);view.innerHTML='<div class="row"><h2 class="grow">Students <span class="muted">'+state.students.filter(s=>s.lowMarks||s.lowAttendance).length+' flagged</span></h2><label>Show<select data-filter><option value="all"'+(state.filter==='all'?' selected':'')+'>All</option><option value="marks"'+(state.filter==='marks'?' selected':'')+'>Low marks</option><option value="attendance"'+(state.filter==='attendance'?' selected':'')+'>Low attendance</option></select></label></div><table><thead><tr><th>Student</th><th>Class</th>'+SUBJECTS.map(s=>'<th>'+s+'</th>').join('')+'<th>Average</th><th>Attendance</th><th>Status</th></tr></thead><tbody>'+rows.map(s=>'<tr><td>'+(canEdit?'<button class="link" data-edit="'+esc(s.id)+'">'+esc(s.name)+'</button>':esc(s.name))+'</td><td>'+esc(s.className||s.classId)+'</td>'+SUBJECTS.map(sub=>{const m=s.marks?s.marks[sub]:null;return '<td'+(m!=null&&m<45?' class="bad"':'')+'>'+(m==null?'&mdash;':m)+'</td>';}).join('')+'<td'+(s.lowMarks?' class="bad"':'')+'>'+(s.average==null?'&mdash;':s.average)+'</td><td'+(s.lowAttendance?' class="bad"':'')+'>'+(s.attendance==null?'&mdash;':s.attendance+'%')+'</td><td>'+(s.lowMarks||s.lowAttendance?[s.lowMarks&&'Low marks',s.lowAttendance&&'Low attendance'].filter(Boolean).join(', '):'OK')+'</td></tr>').join('')+(rows.length?'':'<tr><td colspan="9" class="pad muted">None</td></tr>')+'</tbody></table>'+(state.editing?editForm(state.students.find(s=>s.id===state.editing)): '');}
function editForm(student){if(!student)return'';return '<form id="edit" class="stack pad card"><b>Edit '+esc(student.name)+'</b><div class="row wrap">'+SUBJECTS.map(sub=>'<label>'+sub+'<input name="'+sub+'" type="number" min="0" max="100" value="'+(student.marks&&student.marks[sub]||0)+'"></label>').join('')+'<label>Attendance<input name="attendance" type="number" min="0" max="100" value="'+(student.attendance||0)+'"></label></div><div class="row"><button class="primary" type="submit">Save</button><button type="button" data-cancel>Cancel</button></div></form>';}
function applyStudentEdit(data){const student=state.students.find(s=>s.id===state.editing);if(!student)return null;const marks={};SUBJECTS.forEach(sub=>{marks[sub]=Number(data.get(sub))||0;});const attendance=Number(data.get('attendance'))||0;const v=Object.values(marks);student.marks=marks;student.attendance=attendance;student.average=Math.round(v.reduce((a,b)=>a+b,0)/v.length)||0;student.lowMarks=student.average<PASS_MARK||v.filter(m=>m<45).length>=2;student.lowAttendance=attendance<75;state.editing=null;return student;}
document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;const d=t.dataset;if(t.hasAttribute('data-out')){store.signOut();unsubChat();state.classId=state.threadId=null;renderLogin();}else if(d.tab){state.tab=d.tab;state.editing=null;unsubChat();render();}else if(d.thread){state.threadId=d.thread;unsubChat();renderTab();}else if(d.slot){state.slotId=d.slot;renderTab();}else if(d.edit){state.editing=d.edit;renderTab();}else if(t.hasAttribute('data-clear')||t.hasAttribute('data-cancel')){state.slotId=state.editing=null;renderTab();}else if(t.hasAttribute('data-seed')){try{await store.seed();await refresh();}catch(err){alert(String(err.message||err));}}});
document.addEventListener('submit',async e=>{const f=e.target;e.preventDefault();const fd=new FormData(f);try{if(f.id==='signin'){await store.signIn(fd.get('id'),fd.get('pass'),fd.get('role'));state.classId=state.threadId=null;render();}else if(f.id==='composer'){await store.send(state.threadId,fd.get('text'));const inp=f.querySelector('[name="text"]');if(inp)inp.value='';}else if(f.id==='assign'){await store.setTeacher(state.classId,state.slotId,fd.get('teacher'));await refresh();}else if(f.id==='edit'){const s=applyStudentEdit(fd);if(s)await store.saveStudent(s);await refresh();}}catch(err){if(f.id==='signin')renderLogin(String(err.message||err));else alert(String(err.message||err));}});
document.addEventListener('change',e=>{if(e.target.matches('[data-class]')){state.classId=e.target.value;state.slotId=null;renderTab();}else if(e.target.matches('[data-filter]')){state.filter=e.target.value;renderTab();}});
document.addEventListener('DOMContentLoaded',()=>{boot();});
document.addEventListener('click',async e=>{const b=e.target.closest('#signinbtn');if(b){const f=b.closest('form');if(f){e.preventDefault();const fd=new FormData(f);try{await store.signIn(fd.get('id'),fd.get('pass'),null);state.classId=state.threadId=null;render();}catch(err){renderLogin(String(err.message||err));}}}});